export const SIGN_IN_REQUEST = '[AUTH] SIGN IN REQUEST';
export const SIGN_IN_SUCCESS = '[AUTH] SIGN IN SUCCESS';
export const SIGN_UP_REQUEST = '[AUTH] SIGN UP REQUEST';
export const SIGN_UP_SUCCESS = '[AUTH] SIGN UP SUCCESS';

export const SOCIAL_SIGN_IN = '[AUTH] SOCIAL SIGN IN';

export const AUTH_ERROR = '[AUTH] REQUEST ERROR';
export const CLEAR_AUTH_ERROR = '[AUTH] CLEAR ERROR';
export const SIGN_OUT = '[AUTH] SIGN OUT';
