export const GET_USER_REQUEST = '[USER] GET USER REQUEST';
export const GET_USER_SUCCESS = '[USER] GET USER SUCCESS';
export const GET_USER_ERROR = '[USER] GET USER ERROR';

export const UPDATE_USER_REQUEST = '[USER] UPDATE USER REQUEST';

export const UPDATE_AVATAR_REQUEST = '[USER] UPDATE AVATAR REQUEST';
export const UPDATE_AVATAR_SUCCESS = '[USER] UPDATE AVATAR SUCCESS';
export const UPDATE_AVATAR_ERROR = '[USER] UPDATE AVATAR ERROR';
